[supervisord]
logfile=/root/supervisord.log
user=root
pidfile=/root/ChurnPrediction/logs/supervisord.pid
nodaemon=false
loglevel=DEBUG


[inet_http_server]
port=*:9001
username=t4d
password=t4d_pasword

[program:api]
command=/root/venv/bin/gunicorn --log-config /root/ChurnPrediction/.deploy-services/logging.conf -k uvicorn.workers.UvicornWorker -w 1 --timeout 120 --bind 0.0.0.0:8000 main:app
directory=/root/ChurnPrediction
user=root
stdout_logfile=/root/var/log/gunicorn/output.log
stderr_logfile=/root/var/log/gunicorn/error.log
autostart=true
autorestart=true
startsecs=10
environment=PYTHONUNBUFFERED=1,PYTHONDONTWRITEBYTECODE=1,PYTHONPATH="/root/ChurnPrediction"


[program:streamlit]
command=/root/venv/bin/streamlit run /root/ChurnPrediction/home.py --server.headless=true --server.baseUrlPath=dashboard
user=root
numprocs=1
stdout_logfile=/root/var/log/streamlit/worker.log
stderr_logfile=/root/var/log/streamlit/worker.err.log
autostart=true
autorestart=true
startsecs=10
environment=PYTHONUNBUFFERED=1,PYTHONDONTWRITEBYTECODE=1,PYTHONPATH="/root/ChurnPrediction"